# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a0KA3MeqEjQW7NJJqupKkQfUyuvUTR1D
"""

list=[2,2.5,"Hari"]
print(list)

d=(2,4,12,"Hari")
print(d)

a=[1,2,3]
b=[4,5,6]
c=a+b
print(c)

c=['a','b','c','d','e','f']
print(c[1:3])

print(c[0:-1:1])

a=[2,2.4,23,4]
print(a)
b = a
print(b)







