# -*- coding: utf-8 -*-
"""Python Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UkfxjZbbVXaUAJjHxdWLfb2p4podOojr
"""

a  = 42
print(a)

a=2
b=10
print(a+b)

def add(a,b):
    return a+b
def sub(a,b):
    return a-b
def mul(a,b):
    return a*b
def div(a,b):
    return a/b

n=input("select operator(+,-,*,/): ")
a=float(input("enter first number: "))
b=float(input("enter second number: "))
if n=="+":
    print(f"Addition of {a} and {b} is ",add(a,b))
elif n=="-":
    print(f"Subtraction of {a} and {b} is ", sub(a,b))
elif n=="*":
    print(f"Multiplication of {a} and {b} is ",mul(a,b))
elif n=="/":
    print(f"Division of {a} and {b} is ",div(a,b))
else:
    print("invalid operator")

c=[1,'hello',3.14,True]
print(c)
c.append('world')

print("list after appending",c)

c.remove(3.14)

print("List after removing 3.14 :",c)

t=(1,'apple',3.14,False)
print(t)

print(t[0])

print(t[-1])

for i in range(1,6):
  print(i)

i=1
while i<=5:
    print(i)
    i+=1

n= int(input("Enter a number: "))
if n>0:
  print("number is positive")
elif n<0:
  print('Number is negative')
else:
  print('Number is zero')

def greet(name):
  print("Hello",name)
greet("Alice")

















